version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  app:
    build: .
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo:27017/admin
    ports:
      - "3015:3015"
    depends_on:
      - mongo
